### ISSUE TITLE
[Feature]: Choose custom anchor for SelectContent

### ISSUE THREAD

**Issue by dermitzos** [unovue/radix-vue#1004]
### Describe the feature

I want to build a custom component that combines an Input and a Select box next to each other following the same design and need the SelectContent component to follow the total size of the two combined inputs. 
These are two different inputs and not a Combobox component.

Is there a way to use a custom anchor so SelectContent will follow the size of a different element but just use the select input as the SelectTrigger?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hey @dermitzos , we will be supporting `virtualElement` to all `Popper` floating element in `v2`. I believe you can then pass in a custom position and size for the `SelectContent`

**Comment by zernonia** [comment]
You should be able to pass the any element to `reference` prop in `SelectContent` in `reka-ui@latest` 😁
