### ISSUE TITLE
[Refactor]: change form component from `v-model:checked`/`v-model:pressed` to `v-model` 

### ISSUE THREAD

**Issue by zernonia** [unovue/radix-vue#1017]
### Describe the feature

Many confusion arrises why `v-model` is not working for Form Components in `shadcn-vue`. (https://github.com/radix-vue/shadcn-vue/issues/622 https://github.com/radix-vue/shadcn-vue/issues/121)

To establish the convention among Vue UI library, we will be refactoring form components to use `v-model` as well, namely

1. Toggle
2. Checkbox
3. Switch

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by RayGuo-ergou** [comment]
Hi, will dialogs (e.g. `v-model:open`) be effected too? Just asking so I can prepare myself early for the breaking changes.

**Comment by RayGuo-ergou** [comment]
Cool thanks!

**Comment by zernonia** [comment]
It will be clearer in the v2 docs which component is Form  😁

![image](https://github.com/user-attachments/assets/9c930de9-dc18-4ba9-b220-b1b415e4be7d)

**Comment by RayGuo-ergou** [comment]
This is awesome thanks for your hard work.

**Comment by RayGuo-ergou** [comment]
Spent some time to briefly checked the components above seems only `swtich`, `toggle` and `checkbox` will be changed in v2, for anyone who looked into this topic don't be too worried : )

**Comment by peter-emad99** [comment]
i read the alpha release notes and didn't find any mention for this change ..can we add it to breaking changes section?

**Comment by zernonia** [comment]
@peter-emad99  I think it's missing from the automated generated changelog. Here's the commit in v2
https://github.com/radix-vue/radix-vue/pull/1326/commits/87aa5ba6016fa7a98f02ea43062212906b2633a0

**Comment by zernonia** [comment]
Released in `reka-ui@latest` 😁
