### ISSUE TITLE
[Feature]: Refactor form dependant components

### ISSUE THREAD

**Issue by epr3** [unovue/radix-vue#1046]
### Describe the feature

We should refactor other `input`-like components to be consistent. We should follow the implementation of `NumberField` which has the most features, automatic `form` detection and a `hidden` input which would store the value. 

Components that would need refactor:
- `DatePicker`
- `DateField`
- `DateRangePicker`
- `DateRangeField`
- `PinInput`
- `Select`
- `Listbox`
- `Combobox`
- `Checkbox`
- `Switch`
- `RadioGroup`

Some of these components might not need any updates, but couldn't hurt to check.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
I believe all other than Calendar already have the hidden input field, that would detect form and propagate corresponding value. Check `useFormControl`

**Comment by zernonia** [comment]
Fixed in `reka-ui@latest` 😁
