### ISSUE TITLE
[Feature]:  Allow more types for modelValue in (RadiodGroup, ToggleGroup, CheckboxGroup)

### ISSUE THREAD

**Issue by peter-emad99** [unovue/radix-vue#1093]
### Describe the feature

adding the ability to modelValue type to be number ,boolean, or object not just string
for the components (RadiodGroup, ToggleGroup, CheckboxGroup)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Released on `reka-ui@latest` 😁
