### ISSUE TITLE
[Bug]: checkbox does not dispatch "input" event, like native checkbox

### ISSUE THREAD

**Issue by stefanprobst** [unovue/radix-vue#1209]
### Environment

```bash
Developement/Production OS: linux
Node version: 20.16.0
Package manager: pnpm@9.7.0
Radix Vue version: 1.9.3
Vue version: 3.4.37
Nuxt version: 3.12.4
CSS framework: tailwindcss@3.4.9
Client OS: linux
Browser: firefox
```

### Link to minimal reproduction

https://github.com/stefanprobst/issue-shadcn-vue-checkbox

### Steps to reproduce

- clone the [issue repo](https://github.com/stefanprobst/issue-shadcn-vue-checkbox), `pnpm install`, `pnpm run dev`
- when toggling the native checkboxes, the `<form>` receives input events, and updates the url search params, but when toggling the radix-vue checkboxes, no input events are dispatched

### Describe the bug

see above

### Expected behavior

see above

### Context & Screenshots (if applicable)

note that the react implementation seems to programmatically dispatch the event [here](https://github.com/radix-ui/primitives/blob/main/packages/react/checkbox/src/Checkbox.tsx#L175-L188)

**Comment by epr3** [comment]
@stefanprobst The checkbox component has the same behaviour as the one from the React implementation. 
You would need to add `@click` to the form instead of `@input` because it uses a `button` element. Relevant CodeSandbox: https://codesandbox.io/p/devbox/shadcn-hook-form-68y4d8

@zernonia Would it make sense to stop the propagation of the `click` event on the `Checkbox`, maybe even the `Radio` and any other components which rely on clicks to modify the input value and set up a watcher that dispatches `change` and `input` events?

**Comment by stefanprobst** [comment]
> You would need to add `@click` to the form instead of `@input`

in the example in the issue reproduction, the `@input` handler is also triggered when a user enters text into the `<input name="q" type="search">`. instead of listening to both "click" and "input" events, i think i'd prefer if the fact that the checkbox is implemented as a button is an implementation detail i don't have to know about.

> The checkbox component has the same behaviour as the one from the React implementation

it *does* actually work in react - see https://github.com/stefanprobst/issue-radix-react-checkbox

note that react everywhere uses `onChange` which maps to the behavior of the native input event. from [the react docs](https://react.dev/reference/react-dom/components/input):

![Screenshot_20240811_163312](https://github.com/user-attachments/assets/1c721307-78e0-43fe-9eab-6b8db9f5f247)

**Comment by zernonia** [comment]
Fixed in `reka-ui@latest` 😁

**Comment by Snurppa** [comment]
Hi. Was trying to refactor my checkbox input component to use Reka UI checkbox. My validation library (vee-validate) [works best](https://vee-validate.logaretm.com/v4/guide/composition-api/custom-inputs#building-checkboxes) if I can pass the native HTML input event to vee-validate.

But seems there is no way I can get my hands into it with Reka..?
1. CheckboxRoot has only `update:modelValue` as its emitted event.
2. There is no ref exposed to the input element which does give me ability to "hack into" the input element and listen to its events.

Passing `<input type="checkbox" />` `asChild` results in two inputs rendered inside the form.

I got the impression from this issue that I could've used `@change` event handler with this component.
I was even checking the test file for Checkbox and indeed there isn't any tests regarding emitting "native checkbox events".

Is there some way around this?

Thanks!
