### ISSUE TITLE
[Feature]: Improve NavigationMenu behavior for click-based triggers

### ISSUE THREAD

**Issue by blesildaramirez** [unovue/radix-vue#1304]
### Describe the feature

Currently, the `disableHoverTrigger` prop allows toggling the hover trigger for the `NavigationMenu`, which works as expected. When set to `true`, the menu will activate only on click. However, if the user loses focus or moves the cursor away from the submenu items, the menu closes immediately. I propose keeping the submenu visible until the parent menu is clicked again, providing a more consistent and user-friendly experience.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Due to the limitation of `pointerLeave` event, we have added a new props to prevent pointerLeave to close the content in `reka-ui@latest` 😁

https://reka-ui.com/docs/components/navigation-menu#root `disablePointerLeaveClose `

**Comment by Radiergummi** [comment]
I'm not sure whether I understand how this relates to radix-vue @zernonia; is this actually implemented in this package, or only in reka-ui? I'd like to have a simple navigation menu that can be opened with a click and stays open until the user interacts with a menu item or clicks outside. It seems like there is no easy way to do this right now.

**Comment by blesildaramirez** [comment]
Hi @zernonia , thanks for addressing this issue. Just wanted to ask - when enabling the navigation via click events only, is there a way to just close the opened  <NavigationMenuContent />, only when clicking again on the parent <NavigationMenuItem /> or anywhere within NavigationMenuList but NOT outside of this component? Thanks!
