### ISSUE TITLE
[Feature]: Close NavigationMenuContent on Click and prevent pointerleave

### ISSUE THREAD

**Issue by Moin-chan** [unovue/radix-vue#1315]
### Requesting a property for NavigationMenuContent to be able to close it ONLY on click outside

Current behavior:
When using _:disableHoverTrigger="true"_ on  NavigationMenu component it controls only the opening trigger. But as soon as you leave the content with a pointer - it closes. And I found literally no way how can I prevent or override it. 
I need it to close on a click outside content area.
Here is the video to illustrate: 
https://www.awesomescreenshot.com/video/31821874?key=d79e8b41de5e2bf0caa2ba0ef0f2688c

_disableOutsidePointerEvents_ on NavigationMenuContent is not an option for me, because I have several links in the Content area and it has to be clickable. 
I tried   @pointerenter.prevent with @pointerleave.prevent, @mouseleave.prevent and even @interactOutside, @pointerDownOutside and @focusOutside. No chance. 

It would be great at least to get which event is firing in the background and on which component. Maybe it´s still possible to prevent it. 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Due to the limitation of `pointerLeave` event, we have added a new props to prevent pointerLeave to close the content 😁

https://reka-ui.com/docs/components/navigation-menu#root `disablePointerLeaveClose `
