### ISSUE TITLE
[Bug]: [Vue warn]: Extraneous non-props attributes (data-v-inspector) were passed to component - Nuxt

### ISSUE THREAD

**Issue by HummingMind** [unovue/radix-vue#1320]
### Environment

```
Radix Vue version: latest
Vue version: latest
Nuxt version: latest
```

### Link to minimal reproduction

not needed

### Steps to reproduce

Run nuxt in dev mode when using radix-vue with devtools component inspector enabled (default)

### Describe the bug

[Vue warn]: Extraneous non-props attributes (data-v-inspector) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

You get this warning (many of them):
![image](https://github.com/user-attachments/assets/a66ed99f-dd6f-45bc-a179-c8601cecc661)

Per Daniel Roe - this needs to be fixed on the Radix-Vue side. Here mentioned it is related to vue 3.5 and described the issue here:
[Link](https://github.com/nuxt/nuxt/issues/29002)

### Expected behavior

No warnings should come up

### Context & Screenshots (if applicable)

![image](https://github.com/user-attachments/assets/631085e7-00b7-433a-bd5a-229ae72988a3)

**Comment by hrynevychroman** [comment]
@HummingMind are you using NuxtDevtools? Try to disable `componentInspector` inside `nuxt.config.ts`:

```ts
devtools: { enabled: true, componentInspector: false },
```
I think this is not error inside radix-vue 🙂

**Comment by HummingMind** [comment]
> @HummingMind are you using NuxtDevtools? Try to disable `componentInspector` inside `nuxt.config.ts`:
> 
> ```ts
> devtools: { enabled: true, componentInspector: false },
> ```
> 
> I think this is not error inside radix-vue 🙂

![image](https://github.com/user-attachments/assets/8a78a436-8585-49bd-bf07-cc4849e10d35)

**Comment by sunnylost** [comment]
`DialogRoot` is a `Fragment`, that's why this warning occurred.

**Comment by HummingMind** [comment]
Some info:
[Article 1](https://www.steffenstein.com/blog/how-to-solve-extraneous-non-props-attributes-in-vue-js/)
[Article 2](https://zelig880.com/how-to-solve-extraneous-non-props-attributes-in-vue-js)

**Comment by zernonia** [comment]
@HummingMind  can you share the specific version of Nuxt? we tested locally with Nuxt playground and not showing this warning 😮

**Comment by HummingMind** [comment]
@zernonia 
![image](https://github.com/user-attachments/assets/8756018f-5a37-409e-97a5-dac4a73d2e17)

**Comment by zernonia** [comment]
Thanks @HummingMind ! Correct as @sunnylost  pointed out that some component are `Fragment`, thus triggering this warning. Perhaps we fix it by setting `inheritAttrs: false` with `defineOptions` internally

**Comment by HummingMind** [comment]
@zernonia awesome! I think it's an important fix, as many people use the component inspector in the Nuxt devtools.

Thank you for all your hard work!

**Comment by HummingMind** [comment]
@zernonia just FYI, looks like antfu released nuxt devtools 1.5.2, which downgrades the vite-plugin-vue-inspector to an older 
version that does not cause the warnings to come up. So I can re-enabeld the component inspector without any warnings in radix-vue components.

Not sure what the plan going forward will be, so not sure if you want to keep this issue open or close it out.

**Comment by zernonia** [comment]
Thanks for the update @HummingMind ! I believe we will need to cater for this sooner or later. So anyone wants to pick this up I'll be thrilled! 😁

**Comment by c0nd3v** [comment]
I'm having this problem too
