### ISSUE TITLE
[Feature]: Multi Input

### ISSUE THREAD

**Issue by kaaax0815** [unovue/radix-vue#1375]
### Describe the feature

Add Multi Input component like this
<img width="658" alt="Bildschirmfoto 2024-10-15 um 10 39 48" src="https://github.com/user-attachments/assets/b294eb67-762a-4e47-a113-54d8af04be15">

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hi @kaaax0815 , Reka UI aims to provide primitive component that is missing from the native element. 
Unfortunately, your suggestions doesn't fit into this critieria.
