### ISSUE TITLE
[Feature]: Support `hidden="until-found"` in accordion

### ISSUE THREAD

**Issue by DamianGlowala** [unovue/radix-vue#1376]
### Describe the feature

Context:

https://developer.chrome.com/docs/css-ui/hidden-until-found
https://github.com/adobe/react-spectrum/pull/7199

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the suggestion @DamianGlowala ! Will take a look 😁

**Comment by zernonia** [comment]
Working on this and found an upstream issue if you are using TailwindCSS for styling.  https://github.com/tailwindlabs/tailwindcss/pull/14625

**Comment by zernonia** [comment]
🚀

https://github.com/user-attachments/assets/834f1f45-591c-4e10-b7b0-e4a1da986f75

**Comment by DamianGlowala** [comment]
Beautiful work @zernonia 💯 and yes, saw that Tailwind CSS issue too, good you mentioned it for visibility

> 🚀
> 
>  Screen.Recording.2024-11-07.at.11.31.48.PM.mov

**Comment by zernonia** [comment]
Released in `reka-ui@latest` 😁
