### ISSUE TITLE
[Feature]: Improve threeshaking with webpack 

### ISSUE THREAD

**Issue by chuckmah** [unovue/radix-vue#1377]
### Describe the feature

Currently , the bundling of the lib make it impossible for webpack to properly treeshake. When importing a single primitive the resulting webpack bundle contain all the code from all components and deps of the lib which is like 75kb minified. I guess this is related to an other feature request (https://github.com/unovue/radix-vue/issues/808)

From my investigation this is probably due to https://github.com/vitejs/vite/issues/5174. I patched a radix-vue version using the solution proposed in https://github.com/vitejs/vite/issues/5174#issuecomment-1193414981 and I had proper treeshaking from webpack 5

Here's a snippet of my final patched vite.config.ts file

```
[... rest of the file]
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library (Vue)
      external: ['vue', '@floating-ui/vue', '@internationalized/date', '@internationalized/number'],
      output: {
        preserveModules: true,

        // Provide global variables to use in the UMD build
        // for externalized deps
        globals: {
          'vue': 'Vue',
          '@floating-ui/vue': '@floating-ui/vue',
          '@internationalized/date': '@internationalized/date',
          '@internationalized/number': '@internationalized/number',
        },
        assetFileNames: (chunkInfo) => {
          if (chunkInfo.name === 'style.css')
            return 'index.css'
          return chunkInfo.name as string
        },
      },
    },


```

i'm not proposing this  a proper PR because it probably break other bundler just posting for reference.

Thanks for this great lib

### Additional information

- [ ] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Decided to apply this changes in v2, which is available now on `reka-ui@latest` 😁
