### ISSUE TITLE
[Feature]: Mention Component

### ISSUE THREAD

**Issue by BayBreezy** [unovue/radix-vue#1384]
### Describe the feature

Someone asked me about a feature request. I am not skilled enough to do this type of thing so I am asking you guys for help, please.

Hello! Do you implementing feature requests? If yes I'd appreciate to see something similar to https://www.naiveui.com/en-US/os-theme/components/mention (https://codesandbox.io/s/rfn2nx)

My scenario of usage:

If mention was triggered by : symbol, then show one list of items.
If mention was triggered by @ symbol, then show another list of items.
It should support textarea.
It should support customizable render of list item.
It should optionally support virtual list render? In case there is to much items.
If that's already possible in any way, i'll appreciate any help.

See https://github.com/BayBreezy/ui-thing/issues/14

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
You may checkout this v2 exmaple https://reka-ui.com/examples/combobox-textarea

Currently version v1 has some limitation to achieve the similar effect
