### ISSUE TITLE
[Bug]: SweetAlert2 modal interaction issue with Radix Vue modal: Unable to interact with SweetAlert when triggered inside modal

### ISSUE THREAD

**Issue by AtharFazle** [unovue/radix-vue#1388]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/live/0dcc2817-5888-4d10-8afa-2e70f37a0f7f

### Steps to reproduce

Steps to Reproduce:
1).Open a Radix Vue modal.
2).Trigger a SweetAlert2 inside the modal.
3). Observe that while SweetAlert2 appears in front, it is not clickable, and any interactions (like the "OK" button) do not work, as they are caught by the modal.

### Describe the bug

 I'm experiencing an issue where SweetAlert2 cannot be interacted with when triggered from inside a Radix Vue modal. Although the SweetAlert visually appears in front of the modal, clicks and interactions are still captured by the underlying modal, making the SweetAlert non-functional.

Workaround Attempts:
I tried adjusting the z-index of SweetAlert2 to a higher value (z-[10000]), but it did not resolve the issue.
Used pointer-events: none on the modal to block clicks, but the modal still captures the events.
Attempted to close the modal programmatically before showing SweetAlert, but this is not ideal as it disrupts the workflow.
Checked focus handling and ensured allowOutsideClick is set to false on SweetAlert2.

The issue seems to stem from Radix Vue's modal locking the focus and interactions when the SweetAlert2 dialog appears. This makes SweetAlert unusable without manually closing the modal first, which is not an ideal user experience. I have also tried removing focus lock from Radix Vue's modal, but this hasn't resolved the issue either.

Any help or suggestions on how to ensure SweetAlert2 captures all interactions without closing the modal first would be greatly appreciated!

### Expected behavior

SweetAlert2 should fully capture focus and interactions when triggered, preventing the underlying modal from interfering with any clicks or keyboard interactions.

### Context & Screenshots (if applicable)

https://github.com/user-attachments/assets/25b54f36-703b-4127-97d1-25ddeb163c9a

**Comment by zernonia** [comment]
@AtharFazle  can you please update the reproduction link? It's not working 
![image](https://github.com/user-attachments/assets/0dd007b4-bfa1-495b-9bc0-558dc04db95b)
