### ISSUE TITLE
[Feature]: Tags Input. Support multiple delimiters

### ISSUE THREAD

**Issue by romansp** [unovue/radix-vue#1400]
### Describe the feature

Improve `TagsInputInput` to allow multiple delimiters so that multiple formats of pasted data can be supported.
 
For example I use `TagsInput` component to collect and submit list of email. Occasionally this list will be pasted from other sources for example it may be comma-separated list or tabular data like google sheets.

**Data example**
```
jane.doe@example.com, john.smith@example.com, alex.jones@example.com, taylor.lee@example.com, casey.miller@example.com
```

**Proposed usage**
```tsx
const delimiters = ["\t", "\n\r", "\n", " ", ","]

<TagsInputInput :delimiter="delimiters" />
```

Additionally it would need to strip out empty entries after string split for `modelValue` to be accurate.

Originally for my use-case I was thinking to avoid default `addOnPaste` and implement custom `@paste` handler, but wondering if there's interest to have this functionality built in.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
HAHAHAHA I was about to add this feature request too! 😂

**Comment by zernonia** [comment]
Instead of passing as an array of delimiter, maybe we allow `string | RegExp` as prop?

**Comment by romansp** [comment]
> Instead of passing as an array of delimiter, maybe we allow `string | RegExp` as prop?

I agree `string | RegExp` would be the best since it already fits `String.prototype.split` and `String.prototype.replaceAll` so this feature just comes pretty much for free.

But `string[]` just seems more ergonomic to use than `RegExp` to be honest. So maybe `string | string[] | RegExp` as prop?
