### ISSUE TITLE
[Bug]: [Reka UI] - Could not find a declaration file for module 'reka-ui'.

### ISSUE THREAD

**Issue by BayBreezy** [unovue/radix-vue#1402]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

N/A

### Steps to reproduce

Upgrade to `"reka-ui": "^1.0.0-alpha.2",`

### Describe the bug

After upgrading, I get this in the .vue files that are importing the components
`Could not find a declaration file for module 'reka-ui'.`

Then this in the browser
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/63389d2c-2005-4845-a5df-5eb209493b26">

### Expected behavior

For the imports to work as they did in alpha.1

**Comment by zernonia** [comment]
Thanks @BayBreezy ! Seems like some mistake for the generated types

**Comment by BayBreezy** [comment]
No prob. Thanks for all the hard work 🚀

**Comment by zernonia** [comment]
Thanks for migrating to Reka UI! Do open ticket when you run into issues ya! 😁

**Comment by zernonia** [comment]
Fixed in https://github.com/unovue/radix-vue/releases/tag/v1.0.0-alpha.3

**Comment by BayBreezy** [comment]
Thanks @zernonia
