### ISSUE TITLE
[Feature]: Enable TypeScript `exactOptionalPropertyTypes`

### ISSUE THREAD

**Issue by iamandrewluca** [unovue/radix-vue#1404]
### Describe the feature

It would be great to have the TypeScript `exactOptionalPropertyTypes` option enabled.

https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes

https://youtu.be/krj9KCxJ5OY

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hi @iamandrewluca ! Would love to hear what do you expect for this request ya?

**Comment by iamandrewluca** [comment]
Hi, @zernonia. I will add more details to the task later today.

The YT Video I linked explains why library authors would be better off having this enabled.
In general that change would be that any prop marked as optional via `?` should also have `undefined` in type explicit.

**Comment by iamandrewluca** [comment]
But maybe we are not read for this because of these two 🤔 

- https://github.com/vuejs/core/issues/6532
- https://github.com/vuejs/core/issues/6068

**Comment by iamandrewluca** [comment]
Hey, @zernonia I created a PR in Vue, to add `undefined` to optional properties. That will only allow for native elements to pass `undefined` when `exactOptionalPropertyTypes` is enabled.

In the case of libraries, they also need to mark all their optional props with explicit `undefined` if they want the library to work with `exactOptionalPropertyTypes` enabled.

https://github.com/vuejs/core/pull/12771

**Comment by unrevised6419** [comment]
Hey @zernonia, should I start working on this? I'm getting tired of stumbling on this problem 🙂 

<img width="802" alt="Image" src="https://github.com/user-attachments/assets/fecf95b8-6267-42eb-8aa3-83b7f97fd980" />

An issue template regarding `exactOptionalPropertyTypes`

https://gist.github.com/unrevised6419/8bdfca183fde610708685a60c2510b1e

**Comment by aiktb** [comment]
> Hey [@zernonia](https://github.com/zernonia), should I start working on this? I'm getting tired of stumbling on this problem 🙂
> 
> <img alt="Image" width="802" src="https://private-user-images.githubusercontent.com/1881266/460482305-fecf95b8-6267-42eb-8aa3-83b7f97fd980.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg5Mzg2OTcsIm5iZiI6MTc1ODkzODM5NywicGF0aCI6Ii8xODgxMjY2LzQ2MDQ4MjMwNS1mZWNmOTViOC02MjY3LTQyZWItOGFhMy04M2I3Zjk3ZmQ5ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjdUMDE1OTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc3NGY3MzA5Mjk4MmI0NGNjOTI0ZDNiMDkzZThkYjI0M2YwYTZkNmNkZGI4Njg0NGJiNWNhZDA0OGQ4ZWIzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._Oz9PR6P5jX0Tz4uoy0nlgO_L4oUEjSewCGPI61HLAo">
> An issue template regarding `exactOptionalPropertyTypes`
> 
> https://gist.github.com/unrevised6419/8bdfca183fde610708685a60c2510b1e

Please do this. I can't find a way to fix this TypeScript error without modifying the reka-ui source code. It's really annoying.

**Comment by unrevised6419** [comment]
Note: MUI did this automatically using an ESLint rule they created

PR: https://github.com/mui/material-ui/pull/47750
ESLint Rule PR: https://github.com/mui/mui-public/pull/1032

Will open the issue for now.
