### ISSUE TITLE
[Bug]: can't navigate left/right within ListboxFilter input

### ISSUE THREAD

**Issue by nicooprat** [unovue/radix-vue#1406]
### Environment

```bash
Developement/Production OS: Mac Sonoma
Node version: 22
Package manager: pnpm@9
Radix Vue version: 1.9.7
Vue version: 3.5.12
CSS framework: tailwindcss@3.3.3
Client OS: Mac Sonoma
Browser: Chrome latest
```

### Link to minimal reproduction

https://stackblitz.com/edit/dnpfoa?file=src%2FApp.vue

### Steps to reproduce

Having a Listbox with a ListboxFilter

### Describe the bug

Type some text, hit the left arrow key: nothing happens.

### Expected behavior

It should move the caret left as usual to be able to edit the input text.

### Context & Screenshots (if applicable)

Broken by this change: https://github.com/unovue/radix-vue/pull/1299/files#diff-df087aa6eaf13742aacc211b2d042d7cb0cfbb13ecdaf7b068fb3301b0682337

PR: https://github.com/unovue/radix-vue/issues/1295

**Comment by zernonia** [comment]
Thanks for the issue @nicooprat .. Indeed preventing default for left.right on ListboxFilter is the problem.  
Feel free to submit a PR for this! 😁

**Comment by nicooprat** [comment]
Sorry I wasn't available. Are you sure it's ok to break the feature from https://github.com/unovue/radix-vue/issues/1295 ?
