### ISSUE TITLE
[Feature]: Month Picker, Month Range Picker

### ISSUE THREAD

**Issue by kyselberg** [unovue/radix-vue#1412]
### Describe the feature

Do you consider adding separate month picker, month range picker which is like RangeCalendar?
Maybe it is possible to create such component with existing exposed API but i wasn't able to figure out how(((
If it is possible - i will be greatful for hints

Reference for this feature is on the picture:
<img width="306" alt="Screenshot 2024-11-01 at 14 58 46" src="https://github.com/user-attachments/assets/734076a4-5c32-4d21-9ef7-41023a5d8d9d">

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by epr3** [comment]
Hello @kyselberg,

Would this [Stackblitz](https://stackblitz.com/edit/6m2dpp?file=src%2FApp.vue) help?

It's a Datepicker which has a month and decade view. I'm pretty sure you can replace the components around and use a `RangeCalendar` for your use case.

**Comment by kyselberg** [comment]
@epr3 thanx for replying! this stackblitz example is great!
