### ISSUE TITLE
[Bug]: Safari iOS Dialog BodyScrollLock not working

### ISSUE THREAD

**Issue by 94726** [unovue/radix-vue#1423]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 20.15.0
Package manager: pnpm@3.15.0
Radix Vue version: 1.9.9
Vue version: 3.5.12
Nuxt version: 3.14.159
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.4.14
Client OS: MacOS Version 14.6.1
Browser: Chrome 130.0.6723.117
```

### Link to minimal reproduction

https://www.radix-vue.com/components/dialog.html#nested-dialog

### Steps to reproduce

On iOS Safari:
1. scroll down, such that the native safari footer collapses
2. open dialog
3. scroll outside the dialog

### Describe the bug

This bug allows one to still scroll the body, when a `Dialog` is opened, on mobile safari.

### Expected behavior

Should be able to scroll the body.

### Context & Screenshots (if applicable)

This bug only works when the native safari footer is collapsed (e.g. when previously scrolled down)
Otherwise it behaves as expected 🤷 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/26c6f8b9-85ae-49aa-9080-129562e55d48">
Then it'll allow you to continue to scroll, with the dialog being open.

https://github.com/user-attachments/assets/3d579dca-e46e-405e-84c6-706e01331cc0

**Comment by zernonia** [comment]
related to https://github.com/unovue/radix-vue/issues/575
