### ISSUE TITLE
[Bug]: IME enter key issue in TagsInput

### ISSUE THREAD

**Issue by ty-v1** [unovue/radix-vue#1441]
### Environment

```bash
Node version: v20.12.1
Package manager: pnpm@8.15.6
Radix Vue version: 1.9.10
Vue version: 3.5.13
CSS framework: tailwindcss@3.4.15
OS: macOS 15.1
Browser: Chrome 131.0.6778.86
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-tagsinput-japanse-ime-yh2h2x

### Steps to reproduce

![ime](https://github.com/user-attachments/assets/b2147a6e-35f7-4e55-b945-d614c76fd136)

In this GIF, I tried to add the tag `アメリカ合衆国` (the USA) following these steps:

1. Input `あめりか` (amerika)
2. Select `アメリカ` from the IME candidates
3. Press the Enter key
    * Expected Behavior: The text `アメリカ` remains in the input field, and no tag is added.
    * Actual Behavior: The text `アメリカ` remains in the input field, but an `アメリカ` tag is added.
4. Input `がっしゅうこく` (gassyuukoku)
5. Select `合衆国` from the IME candidates
6. Press the Enter key
    * Expected Behavior: The text `アメリカ合衆国` remains in the input field, and no tag is added.
    * Actual Behavior: The text `合衆国` remains in the input field and a `アメリカ合衆国` tag is added.
7. Press the Enter Key

### Describe the bug

I found an issue related to the Japanese IME in TagsInput.
The Enter key has two functions for IME users:
1. Inputting characters (same as ASCII users)
2. Confirming character conversion

TagsInput cannot handle the second pattern correctly.

Reference: https://en.wikipedia.org/wiki/Japanese_input_method#Kana_to_kanji_conversion

### Expected behavior

TagsInput does not add any tags when user confirms character conversion with the enter key.

**Comment by zernonia** [comment]
@shoma-mano  do you think this is similar to what you fixed https://github.com/unovue/radix-vue/issues/1430 ? 😁
