### ISSUE TITLE
[Bug]: `'"reka-ui"'` has no exported member named `'TimeFieldRootEmits'`

### ISSUE THREAD

**Issue by notadarcy** [unovue/radix-vue#1452]
### Environment

```bash
Developement/Production OS: Windows 11 22621.4317
Node version: 20.17.0
Package manager: pnpm@9.12.3
Reka Ui version: 1.0.0-alpha.5
Vue version: 3.5.12
Client OS: Windows 11 22621.4317
```

### Link to minimal reproduction

-

### Steps to reproduce

Add `import { type TimeFieldRootEmits } from 'reka-ui'` to the code

### Describe the bug

When trying to add the TimeFieldRootEmits type from Reka Ui, the compiler complains that Reka Ui does not export this type

### Context & Screenshots (if applicable)

![Screenshot of the bug](https://github.com/user-attachments/assets/196c1f99-e284-432c-9f63-52e734abae4c)

![Screenshot of the code](https://github.com/user-attachments/assets/c3eabbae-d944-4f14-9c67-9405e08437f7)

**Comment by zernonia** [comment]
Fixed https://github.com/unovue/radix-vue/pull/1326/commits/1842ef8aba7bc211ca40e047426686da08114ae6 😁
