### ISSUE TITLE
[Bug]: DateRangePicker max-value not inclusive

### ISSUE THREAD

**Issue by c00lc0de** [unovue/radix-vue#1455]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://github.com/c00lc0de/radix-vue

### Steps to reproduce

Specify a max-value on the DateRangePickerDefault.story.vue and try to pick this date by double clicking.

### Describe the bug

Double clicking the date specified in max-value leaves the displayed selected date unchanged. The actual date selection seems to be disabled.

### Expected behavior

When double clicking the value specified in max-value on the date should be picked.

### Context & Screenshots (if applicable)

![grafik](https://github.com/user-attachments/assets/14398523-1d24-4b2b-9006-d2c0e3266808)

**Comment by zernonia** [comment]
@epr3  I remember seeing related fix right? 😁

**Comment by epr3** [comment]
@zernonia There was one related to the `DateField` parser, I'll open a PR for this one
