### ISSUE TITLE
[Feature]: Navigation - use CSS properties for indicator and expose position

### ISSUE THREAD

**Issue by gu-stav** [unovue/radix-vue#1470]
### Describe the feature

The indicator of the navigation is currently positioned absolute, without exposing its position:

https://github.com/unovue/radix-vue/blob/82386157c8c5d3a65640b9c4a1b180448612ce8b/packages/core/src/NavigationMenu/NavigationMenuIndicator.vue#L66-L90

It would be nice, if we could access the position through CSS Custom properties similar to Tabs:

https://github.com/unovue/radix-vue/blob/82386157c8c5d3a65640b9c4a1b180448612ce8b/packages/core/src/Tabs/TabsIndicator.vue#L56-L67

This would allow me to position the `NavigationMenuContent` relative to the `NavigationMenuItem` component.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
This is a long-standing issue which also not fixed in `reka-ui` too :'(

**Comment by zernonia** [comment]
@gu-stav  yeah we can add that to css variables. However this will have breaking changes as the indicator will need to be style by the user instead automatic position

**Comment by gu-stav** [comment]
@zernonia Would it make sense to add this to reka-ui instead then, to get it into the 2.0 stable release?
