### ISSUE TITLE
[Feature]: ArrowIcon positioning not implemented

### ISSUE THREAD

**Issue by ankitroviri** [unovue/radix-vue#1484]
### Describe the feature

I cannot change the positioning of ArrowIcon according to my needs. There should be a prop in ArrowIcon to control it' side and sideOffset, like left, right, center.

For example: I wanted to make the dropdown to the left of the trigger icon, but i can't in this case.
![image](https://github.com/user-attachments/assets/0b9f8009-1f38-4ebe-b27e-688ef338431e)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
You can achieve this easily by using `align` prop

https://stackblitz.com/edit/daqwkw?file=src%2FApp.vue

https://www.radix-vue.com/components/popover.html#content
