### ISSUE TITLE
[Bug]: No scrollbars in comboboxes dropdowns

### ISSUE THREAD

**Issue by nicooprat** [unovue/radix-vue#1495]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/s1qasy7v?file=src%2FApp.vue,src%2Fglobal.css

### Steps to reproduce

Open the combobox and scroll among the items

### Describe the bug

Scrollbar hidden

### Expected behavior

Scrollbar displayed

### Context & Screenshots (if applicable)

Why has the native scrollbar been hidden by default? Looks like it's done on purpose: https://github.com/unovue/radix-vue/blob/f9b7af52dc0e66571f0c251b448e9d695985b4cd/packages/radix-vue/src/Combobox/ComboboxViewport.vue#L46-L49

Couldn't find the same behavior in Radix original project.

I'm struggling to revert the behavior, there seem to be a strange bug in Chrome where the scrollbar is usable but invisible when we revert `::-webkit-scrollbar`....

**Comment by zernonia** [comment]
This behavior inline with some other `XViewport` component from Radix, eg `SelectViewport`, `ScrollAreaViewport`. It's by design to hide the scrollbar. 

If you want the scrollbar, just don't wrap the component withint `ComboboxViewport` 😁

**Comment by nicooprat** [comment]
Ok thanks, I didn't know I could omit it without breaking anything, I replaced it with a simple div with overflow: auto.
