### ISSUE TITLE
[Bug]: Undocumented requirement to manually filter virtualized combobox items

### ISSUE THREAD

**Issue by rijenkii** [unovue/radix-vue#1496]
### Environment

```bash
Developement/Production OS: Fedora 41
Node version: 18.20.3
Package manager: 10.2.3
Radix Vue version: Reka 1.0.0-alpha.7
Vue version: latest
Nuxt version: N/A
Nuxt mode: N/A
Nuxt target: N/A
CSS framework: tailwindcss@latest
Client OS: Fedora 41
Browser: Firefox 133.0
```

### Link to minimal reproduction

https://stackblitz.com/edit/cdebpniy

### Steps to reproduce

1. Open the reproduction
2. Click on the right combobox with the placeholder "With virtualizer"
3. Enter "25".
4. Entire list will be shown.

### Describe the bug

When a Combobox is defined with a `<ComboboxVirtualizer>`, the search does not seem to work.

### Expected behavior

Expected only the `number 25` option to be shown, as it does with the combobox labeled "Without virtualizer".

### Context & Screenshots (if applicable)

[Screencast From 2024-12-17 02-32-50.webm](https://github.com/user-attachments/assets/0009f85a-e98e-4c5c-85a7-875dc9ee61c3)

**Comment by rijenkii** [comment]
Seems like you are supposed to filter the items manually before handing them over to the `ComboboxVirtualizer`:
https://github.com/unovue/radix-vue/blob/4823c85b4f12c60a42624b4c1034a6bd5f4675e1/packages/core/src/Combobox/story/ComboboxVirtual.story.vue#L10-L14

So if this is not a bug, then it is certainly needs to be documented. Currently Combobox doesn't even have an example of virtualized usage.

**Comment by zernonia** [comment]
Yo @rijenkii ! we have [Virtualization](https://reka-ui.com/docs/guides/virtualization) section in the docs 😁
