### ISSUE TITLE
[Bug]: Accordion changed when press ArrowDown/ArrowUp on focus element within AccordionContent

### ISSUE THREAD

**Issue by zernonia** [unovue/radix-vue#1504]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.9.11
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/r5xqe4xo?file=src%2FApp.vue

### Steps to reproduce

1. focus on input
2. press ArrowDown

### Describe the bug

The accordion's value was changed

### Expected behavior

It shouldn't change accordion when focus in not on trigger

**Comment by RC-Aid** [comment]
Was this actually fixed? The keyboard behavior on elements within the accordion is totally unexpected
