### ISSUE TITLE
[Feature]: Allow `element` prop of `PopoverAnchor` to accept floating-ui `VirtualElement`

### ISSUE THREAD

**Issue by romansp** [unovue/radix-vue#440]
### Describe the feature

To position floating elements Popover (Popper) uses `floating-ui` internally and floating-ui supports usage of [`VirtualElement` as a reference](https://floating-ui.com/docs/virtual-elements). In particular I'd like to leverage [`contextElement`](https://floating-ui.com/docs/virtual-elements#contextelement) property to ensure correct clipping and position update detection.

The problem arises from type incompatibility where `element` is expected to be of type `Measurable` which expects `getBoundingClientRect(): DOMRect` instead of floating-ui's `ClientRectObject` and doesn't include `contextElement` at all.

Worth mentioning that currently it _just works_ because `PopperContent.vue` [just passes `anchor` from context into `useFloating`](https://github.com/radix-vue/radix-vue/blob/a066730bf659d3a871fb50eb213e71d43ffb9c0b/packages/radix-vue/src/Popper/PopperContent.vue#L253C13-L253C13) so that `floating-ui` computes everything correctly.

Is it something worth changing? If so I'd be willing to work on PR.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hey @romansp  ! Thanks for this feature request! Im thinking about this as well when implementing `Combobox`. Currently we have [ContextMenuTrigger](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/ContextMenu/ContextMenuTrigger.vue#L26-L37) as an example of using virtualEl. 

I believe we can extends a `virtualEl` props with `() => DOMRect` type via `getBoundingClientRect` to any Popper trigger element (eg: DropdownMenuTrigger, ComboboxHeader, etc...) . This would allow dev to precisely anchor the desired popup.

Do you think adding props would achieve the same feature you have in mind?

**Comment by romansp** [comment]
@zernonia it seems that adding props to all `*Trigger` components could also be helpful but it won't achieve the feature I'm proposing.

I'm actually more interested in relaxing `getBoundingClientRect` to a different type instead of `DOMRect`. For example this is how floating-ui defines their `ReferenceElement`.
```ts
type ReferenceElement = Element | VirtualElement;

interface VirtualElement {
  getBoundingClientRect(): ClientRectObject;
  contextElement?: Element;
}

type ClientRectObject = Rect & SideObject;
type Rect = { x: number, y: number, width: number, height: number };
type SideObject = { top: number, right: number, bottom: number, left: number };
```
So their `ClientRectObject` is more relaxed but still conforms to `DOMRect`. This helps to avoid `as DOMRect` cast and allows to use both physical and virtual elements via same prop.

Please also notice presence of `contextElement?: Element`. This property is particularly useful when virtual reference is derived from a real element. In case when `contextElement` is provided floating-ui will attach necessary event listeners to that element and compute its ancestors, for proper clipping calculations and also react to position/size/scroll updates.

**Comment by zernonia** [comment]
Thanks for the detailed explanation @romansp !!
Could you shed some light on how would this feature be introduced in components ya? 😁

**Comment by zernonia** [comment]
Implemented on [v2 - Reka UI](https://reka-ui.com/docs/components/popover#anchor). Instead of only `Measurable`, now the reference prop will takes in`Reference` types 😁
