### ISSUE TITLE
[Feature]: Combobox rendering optimization

### ISSUE THREAD

**Issue by alexbidenko** [unovue/radix-vue#498]
### Describe the feature

`Combobox/ComboboxItem.vue` component contains logic based on `JSON.stringify` function ([example](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Combobox/ComboboxItem.vue#L59)). This is very worst for performance (I have a performance problem on real project now).

`JSON.stringify` is used in current code for identifying every item with `object` value type. But it may be made better.

May to create `getOptionKey: (value: T) => string | number` (where T is generic type of value - https://github.com/radix-vue/radix-vue/issues/466) property what will be calling for every item in computed for create identification variable. Or more simple way: `optionKey: string` property what will be working as static name of unique property of item value (but first variant is more powerful).

Only if `getOptionKey` and `optionKey` are not provided then `JSON.stringify` method might be used.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@alexbidenko  thanks for the suggestion above ya! I wonder if you still have the performance issue after we have updated with generic type, and using `isEqual` from 'fast-deep-equal'

**Comment by zernonia** [comment]
Performance has been fixed in `reka-ui@latest` 😁
