### ISSUE TITLE
[Feature]: Radio: logic customization enhancing

### ISSUE THREAD

**Issue by alexbidenko** [unovue/radix-vue#504]
### Describe the feature

The `RadioGroupItem` component is missing more event emits. It can be very useful when `RadioGroupRoot` and `RadioGroupItem` placed in different components. And component what contains `RadioGroupItem` needs to know about changing too (like in my case).

`changeModelValue` is triggered by `RadioGroupItem` component (https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/RadioGroup/RadioGroupItem.vue#L77) so `RadioGroupItem` component also can trigger `update:model-value` event to outside.

P.S. I think that every component in radix-vue library should trigger more events - it is very useful for developers.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by alexbidenko1998** [comment]
The same problem exists in `ToggleGroupItem` component.

**Comment by NeoN0x** [comment]
Also my use I'm unable to "reset"  the selection as I cannot catch "update:modelValue" since it does not emit anything if the value did not change.

I second that more event can be really useful for customizing logic.

**Comment by zernonia** [comment]
I'm planning to add `select` event when selecting the `Radio`/`RadioGroupItem`. This will be emitted even if `modelValue` doesn't change. You can `@select.prevent` to ignore the default select behavior.

This will probably be extended to `Toggle`/`Checkbox. WDYT @alexbidenko ?

**Comment by alexbidenko** [comment]
@zernonia Nice to hear it! Very useful change)

**Comment by zernonia** [comment]
Implemented according to the above comment. Ready on [Reka UI](https://reka-ui.com/docs/components/radio-group#item)
