### ISSUE TITLE
[Bug]:  Navigation Menu Viewport / Content is incorrectly placed

### ISSUE THREAD

**Issue by nikuscs** [unovue/radix-vue#589]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-navigationmenu-forked-vmm3y2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr2gme4300073b6bjknp46g3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr2gme4300023b6b25onnmx2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr2gme4300043b6b1a2iyf48%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr2gme4300063b6bq1aaybew%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr2gme4300023b6b25onnmx2%2522%253A%257B%2522id%2522%253A%2522clr2gme4300023b6b25onnmx2%2522%252C%2522activeTabId%2522%253A%2522clr2gnaaa00683b6b7hhu9x52%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr2gme4200013b6bsox44spl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clr2gnaaa00683b6b7hhu9x52%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clr2gme4300063b6bq1aaybew%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr2gme4300053b6bqh4bfvq1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr2gme4300063b6bq1aaybew%2522%252C%2522activeTabId%2522%253A%2522clr2gme4300053b6bqh4bfvq1%2522%257D%252C%2522clr2gme4300043b6b1a2iyf48%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr2gme4300033b6bhr05c7w8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clr2gme4300043b6b1a2iyf48%2522%252C%2522activeTabId%2522%253A%2522clr2gme4300033b6bhr05c7w8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Try to set the content to 1 column ( so content flows down ) , adjust the width of the content to lets say 200px.
Use a "standard" desktop viewport on the provided reproduction link, you will notice the arrow will be next to the trigger

### Describe the bug

Video 

https://github.com/radix-vue/radix-vue/assets/12662462/979bceb3-7c63-48c4-9d9d-acfaf9658165

It seems like the this [original radix issue](https://github.com/radix-ui/primitives/issues/1462), the NavigationMenu content cant take a single list of items with a relative small width on the content, otherwise the viewport is not correct positioned, im wondering if its possible to :

- Provide a context of the current position relative to the trigger so we can place the viewport/content in right next to the trigger ( say the arrow already contains this information )
- use FloatUI/popper or similar to correctly position the viewport/content next to the trigger similar to how dropdown works.

### Expected behavior

The content/viewport to be positioned relative to the trigger.

**Comment by zernonia** [comment]
Added `--reka-navigation-menu-viewport-left` and `--reka-navigation-menu-viewport-top` css variables to `NavigationMenuViewport` in `reka-ui@latest`. Then you should be able to position the navgiation based on the computed position 😁
