### ISSUE TITLE
[Feature]: Combobox highlight (?) event

### ISSUE THREAD

**Issue by SuddenDev** [unovue/radix-vue#744]
### Describe the feature

First of all: Thank you guys for your hard work! The library is absolutely amazing!

To my feature reuqest though:
Currently it's not possible (as far as i can tell) to receive an event if or what ComboboxItem is highlighted. You can of course use mouseover, but then it still does not work with hotkeys. In my case, i'd like to (pre)fetch some data based on the current selection, but without the need to actually select the item (for previews for example).

 I've looked into the code and I think most of what's needed is already present. I think we'd just need to expose the event and/or the highlighted selection.
If you guys need help I could try and submit a PR.

Thanks a million already!

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
It will first be introduced in #766, then be made available in 2.0 😁

**Comment by HuakunShen** [comment]
When will 2.0 be released? Really need this feature. Is there an existing branch I can use? 
Or do I have to fork it and write my own if I need it now?

**Comment by zernonia** [comment]
Released on `reka-ui@latest` 😁
