### ISSUE TITLE
[Feature]: Allow more types for modelValue in `Select`

### ISSUE THREAD

**Issue by wouterlms** [unovue/radix-vue#772]
### Describe the feature

Currently, the only supported value is a string, which can be limiting. It would be beneficial to expand this functionality to accommodate additional types, akin to how it's implemented in a Combobox.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by kylemilloy** [comment]
I did a bit of digging on this. While setting this to `any` would be the quick fix I think the better long term solution would be to use a generic for the model value. That said, the package is set to support Vue v3.2 and generics were introduced in v3.3. 

I suspect the reason it's only string would be because when you get values out of `FormData.entries()` it casts them all to strings.

**Comment by wouterlms** [comment]
@kylemilloy, casting the type to `any` wouldn't suffice because the logic for checking if a value is selected is structured like this:

`const isSelected = computed(() => rootContext.modelValue?.value === props.value)`

However, I managed to "fix" it by wrapping the `SelectRoot` and `SelectItem` in custom components where the value is being stringified before passing it.

**Comment by wouterlms** [comment]
This is the workaround for those who are interested:

 `SelectValue` it's quite straightforward

```vue
<script setup lang="ts" generic="TValue">
import { SelectRoot } from 'radix-vue'
import { computed } from 'vue'

const props = defineProps<{
  modelValue: TValue | undefined
}>()

const emit = defineEmits<{
  'update:modelValue': [value: TValue | undefined]
}>()

const model = computed<string | undefined>({
  get: () => {
    return JSON.stringify(props.modelValue)
  },
  set: (value) => {
    if (value === undefined) {
      emit('update:modelValue', undefined)
      return
    }

    emit('update:modelValue', JSON.parse(value))
  },
})
</script>

<template>
  <SelectRoot v-model="model">
    <slot />
  </SelectRoot>
</template>
```

**Comment by kilobyte2007** [comment]
@wouterlms This hack mostly works but you'll also want to handle the `''` empty string to be able to reset the value.

@zernonia are there any plans to expand the types for this component (and others, like Radio Group, Checkbox Group, Toggle Group)?

I think it's implemented quite greatly in the Combobox component so it would probably make sense to replicate this across other components to make it consistent.

**Comment by hi-reeve** [comment]
no update on this one?

**Comment by zernonia** [comment]
As this is highly requested feature, and it involves breaking changes. This will be included in v2

**Comment by MrSunshyne** [comment]
@wouterlms 

> This is my workaround for those who are interested:

thank you for[ this solution ](https://github.com/radix-vue/radix-vue/issues/772#issuecomment-2032993594)🙏 it worked for me!

**Comment by peter-emad99** [comment]
is this feature will be one select component only or it will include the other components aslo ( Radio Group, Checkbox , Toggle Group) ??

**Comment by IceBlizz6** [comment]
> As this is highly requested feature, and it involves breaking changes. This will be included in v2

When can we expect this to be released?

**Comment by timmaier** [comment]
> is this feature will be one select component only or it will include the other components aslo ( Radio Group, Checkbox , Toggle Group) ??

Being able to bind other type values in the the Checkbox, RadioGroup etc would be nice. I'm also having to do the following for checkbox values. There's obviously a case to be made that a backend should handle the string values only and not the objects.

```
<script setup>
import { computed } from 'vue';
import { RadioGroupIndicator, RadioGroupItem, RadioGroupRoot} from 'radix-vue'
import { useFormField } from '@/composables/useFormField';

const props = defineProps({
    items: {
        type: Array,
        required: true,
    },
    valueKey: {
        type: String,
        required: false,
    },
});

const modelValue = defineModel();

// Work around since v-model only accepts string value
// https://github.com/radix-vue/radix-vue/issues/772
const model = computed({
    get: () => {
        if (typeof props.modelValue == 'object') {
            return JSON.stringify(props.modelValue)
        }
        return props.modelValue
    },
    set: (value) => {
        if (value === undefined) {
            emit('update:modelValue', undefined)
            return
        }

        if (typeof value === 'string') {
            emit('update:modelValue', value)
            return
        }

        emit('update:modelValue', JSON.parse(value))
    },
})

const getValue = (item) => {
    if (typeof item === 'string') {
        return item;
    }

    if (typeof item === 'object') {
        return props.valueKey ? item[props.valueKey] : JSON.stringify(item);
    }
};

const { id, name, error, emitFormChange } = useFormField(props);

const errorClasses = computed(() => {
    return {
        'ring-red-500': error.value,
    };
});
</script>

<template>
    {{model}}
    <RadioGroupRoot
        :id="id"
        v-model="model"
        class="flex flex-col gap-2.5"
        :aria-label="name"
        @update:modelValue="emitFormChange"
    >
        <template v-for="(item, iIdx) in items" :key="iIdx">
            <div class="flex items-center">
                <RadioGroupItem
                    :id="item.id"
                    :class="errorClasses"
                    class="bg-white w-4 h-4 ring-gray-200 ring-1 rounded-full hover:bg-teal-200 focus:shadow-black data-[state='checked']:bg-teal-700 outline-none cursor-default"
                    :value="getValue(item)"
                >
                    <RadioGroupIndicator
                        class="flex items-center justify-center w-full h-full relative after:content-[''] after:block after:w-[6px] after:h-[6px] after:rounded-[50%] after:bg-white"
                    />
                </RadioGroupItem>
                <label
                    class="text-black text-sm leading-none pl-4"
                    :for="item.id"
                >
                    {{ item.label }}
                </label>
            </div>
        </template>
    </RadioGroupRoot>
</template>
```

**Comment by NILAXY** [comment]
This update would be greatly appreciated 👍

**Comment by zernonia** [comment]
Added support for more types in [v2 - Reka UI](https://reka-ui.com/docs/components/select#root) 😁

**Comment by jvoros** [comment]
I was struggling with this too.

@wouterlms thank you for your workaround. Helped me come up with this workaround:

```js
<script setup>
const members = [
  {last: 'Starr', first: 'Ringo'},
  {last: 'Harrison', first: 'George'},
  {last: 'Lennon', first: 'John'},
  {last: 'McCartney', first: 'Paul'}
];

const selectedMember = ref();

const selectedMemberParsed = computed(()=> {
  return selectedMember.value ? JSON.parse(selectedMember.value) : null;
});

</script>
<template>
  <SelectRoot v-model="selectedMember">
    <SelectTrigger>
      {{ selectedMember ? `${selectedMemberParsed.first}, ${selectedMemberParsed.last}` : "Select a member" }}
    </SelectTrigger>
    <SelectPortal>
      <SelectContent>
        <SelectViewport>
          <SelectItem v-for="member in members" :value="JSON.stringify(member)">
            {{ member.first }} {{ member.last }}
          </SelectItem>
        </SelectViewport>
      </SelectContent>
    </SelectPortal>
  </SelectRoot>
</template>
```
