### ISSUE TITLE
[Feature]: Add prop to render AccordionContent at all times, but just hide it visually

### ISSUE THREAD

**Issue by Bobakanoosh** [unovue/radix-vue#790]
### Describe the feature

I want to use Accordion, but i also want the text within AccordionContent to be parse-able by crawlers for SEO. Right now, if an AccordionItem is collapsed, the content is deleted from the dom, instead of just hiding it visually.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
I believe this would be extended to Collapsbile component, as Accordion is using it. 👍🏻

**Comment by MickL** [comment]
Is there any ETA on this? I just finished implementing Radix Vue accordion and was about to deploy when I noticed that the item content is removed, and not hidden and there is no option to just hide it.

I want to use the accordion specifically for SEO reasons and need the content to be shown in DOM.

**Comment by MickL** [comment]
@zernonia I see you tagged this as v2. Anyway I feel like it will take too much time and effort for v2 until this gets resolved. It should be a quick fix if I am not wrong.

Here we need the slot either with `v-if` (default) or instead with `v-show` when the new prop is set to true:
https://github.com/unovue/radix-vue/blob/main/packages/radix-vue/src/Collapsible/CollapsibleContent.vue#L101

**Comment by MickL** [comment]
I switched to https://github.com/smastrom/vue-collapsed

**Comment by zernonia** [comment]
We've released [Reka UI Alpha 1](https://github.com/unovue/radix-vue/releases/tag/v1.0.0-alpha.1) which included the fix. 😁
