### ISSUE TITLE
[Feature]: Ability to select the first item with Enter keydown even if it is not highlighted on Listbox

### ISSUE THREAD

**Issue by ucyildirim** [unovue/radix-vue#876]
### Describe the feature

When filtering results in the `Listbox` component using `<ListboxFilter />`, it is necessary to highlight one of the results so that it can be selected with the Enter key.

I think that if any filter has been entered, pressing the Enter key should automatically select the first result, even if it is not highlighted

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hmm.. I think it's better to auto highlight the option when you filter the list. This way it provide visual cue to the usual that the item can be selected via "Enter".

**Comment by zernonia** [comment]
Fixed in `reka-ui@latest` 😁
