### ISSUE TITLE
[Feature]: ComboboxInput support custom to element already exist

### ISSUE THREAD

**Issue by aquarius-wing** [unovue/radix-vue#891]
### Describe the feature

The scenario I hope for this feature is that in a rich text editor, you often need to use / to call up the menu and then search.

At this time, the most natural way is that you are still typing in the editor and can also search for the called-up menu. At this point, ComboboxInput should not be a separate input, but it would be best if it could be re-designated as an existing contenteditable=true dom.

https://github.com/radix-vue/radix-vue/assets/16633962/539b267a-dea3-4d92-b4ea-e81e2aafe049

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks @aquarius-wing . I had this idea as well as to allow the `input` to be virtual. However this require some refactoring, and I'll set it to be part of v2

**Comment by aquarius-wing** [comment]
> Thanks @aquarius-wing . I had this idea as well as to allow the `input` to be virtual. However this require some refactoring, and I'll set it to be part of v2

That's nice to hear about it!

**Comment by zernonia** [comment]
Released on `reka-ui@latest`. You may check out given example https://reka-ui.com/examples/combobox-textarea 😁
