### ISSUE TITLE
[Feature]: Standalone time picker

### ISSUE THREAD

**Issue by dword-design-honestly** [unovue/radix-vue#900]
### Describe the feature

I was looking for a Vue 3 time picker and didn't find much. Then found Radix Vue and thought that this framework could need a standalone time picker with a nice dropdown.

Additional question: Is it possible to add a time picker to a date picker?

**Comment by sadeghbarati** [comment]
> Additional question: Is it possible to add a time picker to a date picker

Yes, it can be done with `@internationalized/date` pkg, I think we can even create Time Picker with it but, I need to check the docs to find out the way

Meanwhile, you can check this source

https://github.com/damianricobelli/shadcn-cal-com/
https://shadcn-cal-com.vercel.app

**Comment by zernonia** [comment]
Or perhaps can be fixed by https://github.com/radix-vue/radix-vue/issues/555

**Comment by dword-design-honestly** [comment]
Drop-down time picker like [vue2-timepicker](https://phoenixwong.github.io/vue2-timepicker/) would be great.

**Comment by zernonia** [comment]
Seeing there's multiple request for this component, perhaps we can create one with https://react-spectrum.adobe.com/react-spectrum/TimeField.html as reference 😁
