### ISSUE TITLE
[Feature]: Allow mounting navigation menu children even if they are not hovered

### ISSUE THREAD

**Issue by kilobyte2007** [unovue/radix-vue#902]
### Describe the feature

For SEO purposes it would make sense to be able to make the navigation menu items to still be rendered but hidden even if they are not hovered/clicked.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Add `:unmountOnHide="false"` prop on `NavigationMenuRoot` to render content even the element is hidden. 
Released on `reka-ui@latest` 😁
