### ISSUE TITLE
[Feature]: Imperatively select a ListboxItem

### ISSUE THREAD

**Issue by noghartt** [unovue/radix-vue#934]
### Describe the feature

I have an external input that I would like to, based on some keybinds, highlight a specific item of my Listbox. Is there a way to do it?

If not, I think that would be cool if it could be possible.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
We have exposed [`highlightItem`](https://github.com/unovue/radix-vue/commit/a447bd130264b9128fb40ae8e21226601df19d87#diff-56939a4dbadfdf10e945e9b1038ed32fd072e8d57aa576db5a302c9c0554fee0R321-R321) so you can control the highlight 
in `reka-ui@latest` 😁
