### ISSUE TITLE
[Bug]: Checkbox not applying scoped styles

### ISSUE THREAD

**Issue by dfagan2** [unovue/radix-vue#945]
### Environment

```bash
Developement/Production OS: Mac Sonoma 14.3.1
Node version: 20.11.1
Package manager: pnpm@9.0.6
Radix Vue version: 1.7.3
Vue version: 3.0.0
CSS framework: SASS
Client OS: Windows Mac Sonoma 14.3.1
Browser: Chrome 124.0.6367.91
```

### Link to minimal reproduction

https://stackblitz.com/edit/jfmkua?file=src%2FApp.vue

### Steps to reproduce

- Forked the Checkbox Stackblitz
- Moved some of the styles from the global `style.css` to a `<style scoped>` block in the `.vue` file

### Describe the bug

The Checkbox component does not apply styles for rules bound to a class defined in a `<style scoped>` block. It appears the CheckboxRoot is not attaching the `data-v-[random]` attribute to the rendered `<button>`. Copying-pasting that attribute from a sibling element in Chrome Devtools fixes it. Of note, this all works fine for the Radio.

Our workaround was to use `asChild` like below, but would prefer not to have to hack it.
```
<CheckboxRoot ... asChild>
    <button>
        ...
    </button>
</CheckboxRoot>
```

### Expected behavior

Able to use scoped styles in a single file component using Checkbox, like we're able to for Radio

### Context & Screenshots (if applicable)
(box unstyled while sibling label is styled)
<img width="285" alt="Screenshot 2024-05-21 at 10 31 37 AM" src="https://github.com/radix-vue/radix-vue/assets/769972/83f644bb-ab14-49d3-9327-cffacb67a5b6">

**Comment by zernonia** [comment]
Thanks for the issue @dfagan2 ! I believe this is happening because in `CheckboxRoot`, we have multiple root node (additional `input` to cater for native form submission), thus the scoped data-attribute doesn't attached correctly to it. 

Will look into this ASAP! 😁

**Comment by epr3** [comment]
@zernonia It looks like Vue 3 skips adding scoped styles on multi-root components, according to this issue here: https://github.com/vuejs/core/issues/5446

Would it be beneficial to have the hidden `input` as a child of the root `Primitive` component (just below the `<slot>`)?

**Comment by zernonia** [comment]
@epr3  I think we can do that. Since many component are doing the same, where visually hidden input were placed inside `Primitive`. However I would like this to be done in `v2` instead of minor release. (I had a hunch it might cause some UI styling issue)

**Comment by TheKvikk** [comment]
This is also happening with Switch component. If example code is used SwitchRoot is rendered as button without data-v-[id].

**Comment by zernonia** [comment]
Yup. Some form components were having multiple root nodes thus causing scoped styles wasn't being applied correctly. It will be fixed in v2 😁

**Comment by zernonia** [comment]
Related ticket https://github.com/vuejs/core/issues/6861

**Comment by zernonia** [comment]
Fixed in [reka-ui@latest] 😁
