### ISSUE TITLE
[Feature]: Checkbox for multiple choice selections

### ISSUE THREAD

**Issue by ChrisGV04** [unovue/radix-vue#973]
### Describe the feature

Currently, the `Checkbox` only supports boolean controlled values. However, the native `<input type="checkbox" />` also does support adding a value to an array when you pass the `value=""` attribute to it. Although `Checkbox` accepts the `value` prop, it doesn't add the value to an array if you want to use it in a controlled manner.

For example:

```vue
<script setup lang="ts">
import { CheckboxIndicator, CheckboxRoot } from 'radix-vue';
import { ref } from 'vue';

const selection = ref<string[]>([]);
</script>

<template>
  <div>
    <h1>Choose your favorite foods</h1>

    <div class="flex items-center gap-2">
      <CheckboxRoot v-model:checked="selection" value="pizza" name="selection" id="pizza">
        <CheckboxIndicator>&check;</CheckboxIndicator>
      </CheckboxRoot>

      <label for="pizza">Pizza 🍕</label>
    </div>

    <div class="flex items-center gap-2">
      <CheckboxRoot v-model:checked="selection" value="tacos" name="selection" id="tacos">
        <CheckboxIndicator>&check;</CheckboxIndicator>
      </CheckboxRoot>

      <label for="tacos">Tacos 🌮</label>
    </div>

    <div class="flex items-center gap-2">
      <CheckboxRoot v-model:checked="selection" value="hamburger" name="selection" id="hamburger">
        <CheckboxIndicator>&check;</CheckboxIndicator>
      </CheckboxRoot>

      <label for="hamburger">Hamburger 🍔</label>
    </div>
  </div>
</template>
```

That doesn't work as of v1.8.2, but the native `input` element with Vue would add the `value` attribute to the `selection` array once the checkbox is checked.

The native checkbox behavior in Vue: https://vuejs.org/guide/essentials/forms.html#checkbox

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by AndreiHudovich** [comment]
@zernonia It would be awesome to have this functionality also for the Switch element, if this is technically possible.

**Comment by zernonia** [comment]
@AndreiHudovich  this is kinda against the design of [RadioGroup](https://www.w3.org/WAI/ARIA/apg/patterns/radio/) 😅

> A radio group is a set of checkable buttons, known as radio buttons, where no more than one of the buttons can be checked at a time.

**Comment by AndreiHudovich** [comment]
> @AndreiHudovich  That is kinda against the design of [RadioGroup](https://www.w3.org/WAI/ARIA/apg/patterns/radio/) 😅
> 
> 
> 
> > A radio group is a set of checkable buttons, known as radio buttons, where no more than one of the buttons can be checked at a time. 

But Switch is just a checkbox, no?

**Comment by zernonia** [comment]
@AndreiHudovich  I read wrongly just now hahahaha! Technically it's possible with `Switch` too 😁

**Comment by romanhrynevych** [comment]
Maybe something like this CheckboxGroup in OG radix will be great 🤔 
[link](https://www.radix-ui.com/themes/docs/components/checkbox-group)

**Comment by sugoidesune** [comment]
I fixed this using AI in . But it doesn't support arrays of objects. And I don't think it's easily possible without a radix-vue update.

Please don't overcomplicate the (re-) implementations.
- it creates bugs
- it's hard to find them
- it's hard to contribute solutions

just forward the binding of v-model and it would all work.

Debugging this checkbox took hours, because it is the last thing i expected to not work.

https://github.com/radix-vue/shadcn-vue/issues/759
https://github.com/radix-vue/shadcn-vue/issues/622

**Comment by zernonia** [comment]
Added CheckboxGroup in `reka-ui@latest`. 

[Example](https://reka-ui.com/examples/checkbox-group). Doc will be updating soon.
